[package]
name = "uring-async"
version = "0.0.0"
edition = "2021"

[dependencies]
rustix = { version = "0.38", features = ["io_uring", "mm"] }
futures = { version = "0.3.30", features = ["executor"] }

[dev-dependencies]
rustix = { version = "0.38", features = ["pipe"] }
