style_edition = "2024"
condense_wildcard_suffixes = true
format_code_in_doc_comments = true
hard_tabs = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
